### ISSUE TITLE
404 on delete

### ISSUE THREAD

**Issue by pmbsa** [jenkinsci/artifact-promotion-plugin#15]
Hi, can you think of anything obvious that might be causing a 404 on the delete step. everything else is working a treat, artifacts downloadd from staging and uploaded to release but for some reason the delete step fails. 

thanks
Paul

**Comment by pmbsa** [comment]
hmm, I suspect the issue is because I am using Nexus 3 which apparently is very short of a rest api. Very sad indeed, being able to delete the staged artefact is pretty imprortant. Oh well. Great little plugin by the way. very useful

**Comment by hcguersoy** [comment]
Hello Paul,

indeed I don't have tested the plugin with Nexus 3 yet so this is maybe due to the changes in the API.

**Comment by hcguersoy** [comment]
@pmbsa Just FYI: I plan to fix this in the near future. I can't tell yet then but it's in my backlog. Stay tuned.

**Comment by hcguersoy** [comment]
I've checked this. Unfortunately there is none API endpoint in Nexus 3.x which I can use to delete unneeded artifacts (or I simply missed it). 
Due to that currently I can't fix this :-(

**Comment by pmbsa** [comment]
:D thanks for trying... Nexus 3 seems to be very very lite on anything useful as far as API is concerned so I am not surprised. I now regret my choice to use it at all... Oh well, we will have to wait until it matures and hopefully then we will see something more useful... I am a bit confounded why sonatype even released it to the public actually.
