### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/artifact-promotion-plugin#16]
Hi,

Very nice and useful plugin - Thank you!

Do you have an idea how can I promote the latest version without writing the specific version?

Ido

**Comment by idokaplan** [comment]
Hi,

Is there any update?

Thanks
Ido

**Comment by hcguersoy** [comment]
Hello @idokaplan 

unfortunately in the plugin hard coded versions are used, a usage of version ranges is not supported.
