### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/artifact-promotion-plugin#17]
Hi,

I have two questions, maybe you can advise.

1. Promote multiple packages (latest) in the same build.

2. Get a list of all the packages (name and version) from "Groupid" and to choose with package to promote.

Thanks!
Ido

**Comment by hcguersoy** [comment]
Hello @idokaplan ,

currently the plugin doesn't support promotion of multiple artifacts in one step (e.g. multiple extensions, multiple artifactID's etc.) but have the first one (multiple artifacts e.g. with same coordinates but different extension or qualifiers) on my todo list.

The second question: in this point I would suggest to write a little groovy script to retrieve this informations out of Nexus - I wouldn't like to see such functionality in the plugin itself as this would prerequisites user interaction.
